# Generated by Django 4.2.21 on 2025-09-05 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasa', models.CharField(help_text='Ex: 6A, 7B, etc.', max_length=10)),
                ('scoala', models.CharField(blank=True, max_length=200)),
                ('telefon_parinte', models.CharField(blank=True, max_length=15)),
                ('email_parinte', models.EmailField(blank=True, max_length=254)),
                ('ore_start', models.TimeField(default='08:00', help_text='Ora de început a programului școlar')),
                ('durata_ora', models.IntegerField(default=50, help_text='Durata unei ore în minute')),
                ('durata_pauza', models.IntegerField(default=10, help_text='Durata pauzei în minute')),
                ('nr_ore_pe_zi', models.IntegerField(default=7, help_text='Numărul maxim de ore pe zi')),
                ('reminder_teme', models.BooleanField(default=True, help_text='Notificări pentru teme')),
                ('reminder_note', models.BooleanField(default=True, help_text='Notificări pentru note noi')),
                ('zile_reminder_teme', models.IntegerField(default=1, help_text='Cu câte zile înainte să anunțe temele')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Student',
                'verbose_name_plural': 'Profile Studenți',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('tema', 'Temă de făcut'), ('nota', 'Notă nouă'), ('absenta', 'Absență nouă'), ('reminder', 'Reminder general'), ('sistem', 'Notificare sistem')], max_length=20)),
                ('titlu', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('link_url', models.URLField(blank=True, help_text='Link către pagină relevantă')),
                ('citita', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificări',
                'ordering': ['-created_at'],
            },
        ),
    ]
