# Generated by Django 4.2.7 on 2025-09-17 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_studentprofile_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approved',
            field=models.BooleanField(default=False, help_text='Contul a fost aprobat de un administrator'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administratorul care a aprobat contul', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
