# Generated by Django 4.2.21 on 2025-09-05 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(help_text='Ex: Semestrul 1, Semestrul 2', max_length=100)),
                ('descriere', models.TextField(blank=True)),
                ('activ', models.BooleanField(default=False, help_text='Template-ul activ în prezent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Orar',
                'verbose_name_plural': 'Template-uri Orar',
                'ordering': ['-activ', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi_saptamana', models.IntegerField(choices=[(1, 'Luni'), (2, 'Marți'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri')], help_text='1=Luni, 2=Marți, etc.')),
                ('ora_inceput', models.TimeField(help_text='Ora de început')),
                ('ora_sfarsit', models.TimeField(help_text='Ora de sfârșit')),
                ('sala', models.CharField(blank=True, help_text='Sala specifică pentru această oră', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Note speciale pentru această oră')),
                ('numar_ora', models.PositiveIntegerField(help_text='A câta oră din zi (1, 2, 3, etc.)')),
                ('tip_ora', models.CharField(choices=[('normal', 'Oră normală'), ('dirigentie', 'Ora de dirigentie'), ('optionala', 'Oră opțională'), ('recuperare', 'Oră de recuperare')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intrare Orar',
                'verbose_name_plural': 'Intrări Orar',
                'ordering': ['zi_saptamana', 'numar_ora'],
                'unique_together': {('user', 'zi_saptamana', 'numar_ora')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_schimbare', models.CharField(choices=[('anulata', 'Oră anulată'), ('mutata', 'Oră mutată'), ('inlocuita', 'Materie înlocuită'), ('sala_schimbata', 'Sala schimbată'), ('profesor_inlocuitor', 'Profesor înlocuitor')], max_length=20)),
                ('data_start', models.DateField(help_text='De la această dată')),
                ('data_end', models.DateField(blank=True, help_text='Până la această dată (opțional)', null=True)),
                ('motiv', models.CharField(blank=True, help_text='Motivul schimbării', max_length=200)),
                ('ora_inceput_noua', models.TimeField(blank=True, null=True)),
                ('ora_sfarsit_noua', models.TimeField(blank=True, null=True)),
                ('sala_noua', models.CharField(blank=True, max_length=20)),
                ('profesor_inlocuitor', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='schedule.scheduleentry')),
                ('subject_nou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes_new', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schimbare Orar',
                'verbose_name_plural': 'Schimbări Orar',
                'ordering': ['-data_start'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi_saptamana', models.IntegerField(choices=[(1, 'Luni'), (2, 'Marți'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri')])),
                ('ora_inceput', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('sala', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('numar_ora', models.PositiveIntegerField()),
                ('tip_ora', models.CharField(choices=[('normal', 'Oră normală'), ('dirigentie', 'Ora de dirigentie'), ('optionala', 'Oră opțională'), ('recuperare', 'Oră de recuperare')], default='normal', max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_entries', to='schedule.scheduletemplate')),
            ],
            options={
                'verbose_name': 'Intrare Template Orar',
                'verbose_name_plural': 'Intrări Template Orar',
                'ordering': ['zi_saptamana', 'numar_ora'],
                'unique_together': {('template', 'zi_saptamana', 'numar_ora')},
            },
        ),
    ]
