# Generated by Django 4.2.7 on 2025-09-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(help_text='Ex: 6A, 7B', max_length=20, unique=True)),
                ('scoala', models.CharField(blank=True, max_length=200)),
                ('descriere', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diriginte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clasă',
                'verbose_name_plural': 'Clase',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi_saptamana', models.IntegerField(choices=[(1, 'Luni'), (2, 'Marți'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri')], help_text='1=Luni, 2=Marți, etc.')),
                ('numar_ora', models.PositiveIntegerField(help_text='A câta oră din zi (1, 2, 3, etc.)')),
                ('ora_inceput', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('subject_name', models.CharField(help_text='Numele materiei (ex: Matematică)', max_length=100)),
                ('subject_color', models.CharField(default='#007bff', help_text='Culoare în format hex (#FF5733)', max_length=7)),
                ('sala', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('tip_ora', models.CharField(choices=[('normal', 'Oră normală'), ('dirigentie', 'Ora de dirigentie'), ('optionala', 'Oră opțională'), ('recuperare', 'Oră de recuperare')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule.classroom')),
            ],
            options={
                'verbose_name': 'Intrare Orar Clasă',
                'verbose_name_plural': 'Intrări Orar Clasă',
                'ordering': ['class_room', 'zi_saptamana', 'numar_ora'],
                'unique_together': {('class_room', 'zi_saptamana', 'numar_ora')},
            },
        ),
    ]
