# Generated by Django 4.2.7 on 2025-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classroom_classscheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='judet',
            field=models.CharField(blank=True, help_text='Județul școlii (ex: București, Cluj)', max_length=50),
        ),
    ]
