# Generated by Django 4.2.21 on 2025-09-05 14:03

import apps.subjects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(help_text='Ex: Matematică, Română, Engleză', max_length=100)),
                ('nume_profesor', models.CharField(blank=True, max_length=100)),
                ('sala', models.CharField(blank=True, help_text='Ex: A1, B5, etc.', max_length=20)),
                ('culoare', models.CharField(default='#007bff', help_text='Culoare în format hex (#FF5733)', max_length=7)),
                ('descriere', models.TextField(blank=True, help_text='Note despre materie')),
                ('manual', models.CharField(blank=True, help_text='Numele manualului folosit', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Materia se mai studiază în acest semestru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materie',
                'verbose_name_plural': 'Materii',
                'ordering': ['nume'],
                'unique_together': {('user', 'nume')},
            },
        ),
        migrations.CreateModel(
            name='SubjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('continut', models.TextField()),
                ('important', models.BooleanField(default=False, help_text='Notița este importantă')),
                ('tags', models.CharField(blank=True, help_text='Tag-uri separate prin virgulă', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Notiță Materie',
                'verbose_name_plural': 'Notițe Materii',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(help_text='Numele afișat pentru fișier', max_length=200)),
                ('fisier', models.FileField(upload_to=apps.subjects.models.subject_file_upload_path)),
                ('tip', models.CharField(choices=[('document', 'Document'), ('imagine', 'Imagine'), ('audio', 'Audio'), ('video', 'Video'), ('altele', 'Altele')], default='document', max_length=20)),
                ('descriere', models.TextField(blank=True)),
                ('marime', models.PositiveIntegerField(blank=True, help_text='Mărime în bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Fișier Materie',
                'verbose_name_plural': 'Fișiere Materii',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
