# Generated by Django 4.2.7 on 2025-09-08 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, help_text='Importanța materiei (1-5 stele)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
