from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='valoare',
            field=models.DecimalField(
                max_digits=4,
                decimal_places=2,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                blank=True,
                null=True,
                help_text='Valoarea notei (1.00 - 10.00). Nu se completează pentru absențe.',
            ),
        ),
    ]

# Generated by Django 4.2.7 on 2025-09-17 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='valoare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valoarea notei (1.00 - 10.00). Nu se completează pentru absențe.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
