# Generated by Django 4.2.7 on 2025-09-17 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_valoare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradegoal',
            name='media_dorita',
            field=models.DecimalField(decimal_places=2, help_text='Media dorită pentru această materie', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='subjectgradestats',
            name='nota_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subjectgradestats',
            name='nota_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
