# Generated by Django 4.2.7 on 2025-09-17 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_gradegoal_media_dorita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-an_scolar', '-numar'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='semestru',
            field=models.PositiveIntegerField(help_text='Modulul (1–5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='semester',
            name='activ',
            field=models.BooleanField(default=False, help_text='Modulul activ în prezent'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='numar',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
