# Generated by Django 4.2.21 on 2025-09-05 14:03

import apps.homework.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(help_text='Titlul temei', max_length=200)),
                ('descriere', models.TextField(help_text='Descrierea detaliată a temei')),
                ('pagini', models.CharField(blank=True, help_text='Ex: pag. 25-30, ex. 1-5', max_length=100)),
                ('exercitii', models.TextField(blank=True, help_text='Detalii despre exerciții')),
                ('data_primita', models.DateField(default=datetime.date.today, help_text='Când a fost dată tema')),
                ('deadline', models.DateField(help_text='Până când trebuie făcută tema')),
                ('prioritate', models.CharField(choices=[('scazuta', 'Scăzută'), ('normala', 'Normală'), ('ridicata', 'Ridicată'), ('urgenta', 'Urgentă')], default='normala', max_length=20)),
                ('dificultate', models.CharField(choices=[('usoara', 'Ușoară'), ('medie', 'Medie'), ('grea', 'Grea')], default='medie', max_length=20)),
                ('timp_estimat', models.PositiveIntegerField(blank=True, help_text='Timp estimat în minute pentru finalizare', null=True)),
                ('timp_lucrat', models.PositiveIntegerField(default=0, help_text='Timp efectiv lucrat în minute')),
                ('progres', models.PositiveIntegerField(default=0, help_text='Progres în procente (0-100)')),
                ('finalizata', models.BooleanField(default=False)),
                ('data_finalizare', models.DateTimeField(blank=True, null=True)),
                ('reminder_activ', models.BooleanField(default=True)),
                ('zile_reminder', models.PositiveIntegerField(default=1, help_text='Cu câte zile înainte de deadline să trimită reminder')),
                ('note_personale', models.TextField(blank=True, help_text='Notițe personale despre temă')),
                ('dificultati', models.TextField(blank=True, help_text='Dificultăți întâmpinate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_set', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temă',
                'verbose_name_plural': 'Teme',
                'ordering': ['deadline', '-prioritate'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inceput', models.DateTimeField(auto_now_add=True)),
                ('sfarsit', models.DateTimeField(blank=True, null=True)),
                ('durata_minute', models.PositiveIntegerField(default=0)),
                ('progres_inainte', models.PositiveIntegerField(default=0)),
                ('progres_dupa', models.PositiveIntegerField(default=0)),
                ('note_sesiune', models.TextField(blank=True, help_text='Ce s-a făcut în această sesiune')),
                ('dificultati_sesiune', models.TextField(blank=True, help_text='Probleme întâmpinate')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='homework.homework')),
            ],
            options={
                'verbose_name': 'Sesiune Lucru Temă',
                'verbose_name_plural': 'Sesiuni Lucru Teme',
                'ordering': ['-inceput'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(help_text='Numele fișierului', max_length=200)),
                ('fisier', models.FileField(upload_to=apps.homework.models.homework_file_upload_path)),
                ('tip', models.CharField(choices=[('resursa', 'Resursă pentru temă'), ('solutie', 'Soluția mea'), ('imagine', 'Imagine/Screenshot'), ('document', 'Document'), ('altele', 'Altele')], default='altele', max_length=20)),
                ('descriere', models.TextField(blank=True)),
                ('marime', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.homework')),
            ],
            options={
                'verbose_name': 'Fișier Temă',
                'verbose_name_plural': 'Fișiere Teme',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reminder', models.DateField()),
                ('ora_reminder', models.TimeField(default='18:00')),
                ('trimis', models.BooleanField(default=False)),
                ('data_trimitere', models.DateTimeField(blank=True, null=True)),
                ('mesaj_custom', models.TextField(blank=True, help_text='Mesaj personalizat pentru reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='homework.homework')),
            ],
            options={
                'verbose_name': 'Reminder Temă',
                'verbose_name_plural': 'Reminder-uri Teme',
                'ordering': ['data_reminder', 'ora_reminder'],
                'unique_together': {('homework', 'data_reminder')},
            },
        ),
    ]
