# Generated by Django 4.2.7 on 2025-09-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classroom_classscheduleentry'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='share_with_class',
            field=models.BooleanField(default=False, help_text='Dacă este activat, tema va fi vizibilă tuturor elevilor din clasa setată în profilul tău.'),
        ),
        migrations.AddField(
            model_name='homework',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='shared_class_room',
            field=models.ForeignKey(blank=True, help_text='Clasa cu care este partajată tema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_homeworks', to='schedule.classroom'),
        ),
    ]
